spring:
  application:
    name: shortform
  devtools:
    restart:
      enabled: false
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  datasource:
    url: ${ORACLE_DB_URL}
    driver-class-name: oracle.jdbc.OracleDriver
    username: C##FIN
    password: ${ORACLE_DB_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 10000
      idle-timeout: 10000
      max-lifetime: 580000
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 200
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.OracleDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:9005/login/oauth2/code/google
            scope: email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email
  flyway:
    # enabled: false
    baseline-version: 1
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${ORACLE_DB_URL}
    user: C##FIN
    password: ${ORACLE_DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
      # password:
      # database: 0
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

server:
  port: 9005
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: true
  servlet:
    encoding:
      charset: UTF-8
    session:
      timeout: 20h
    context-path: /
  forward-headers-strategy: native
  tomcat:
    threads:
      max: 500
    connection-timeout: 60000

mybatis:
  mapper-locations: classpath:/mappers/*/*.xml
  type-aliases-package: com.e.shortform.domain.*.res, com.e.shortform.domain.*.vo

logging:
  level:
    com.zaxxer.hikari: warn

jwt:
  secret: LoremaipsumadolorasitaametaconsecteturaaadipisicingaelitaaVoluptasanatusaasapienteaundeacommodiaharumaprovidentanobisaaRecusandaeaatemporeaprovidentaquasiahicaminimaaveroalaboriosamavoluptatesanonaminusamagniaenimavoluptatibus
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html      # Swagger UI 활성화 여부 (기본값: true)
    enabled: true               # 태그 정렬 방식 (기본값: alpha - 알파벳 순)
    tags-sorter: alpha          # Operation 정렬 방식 (기본값: method - HTTP 메서드 순)
    operations-sorter: method   # OpenAPI 문서(JSON/YAML)의 경로 설정 (기본값: /v3/api-docs)
    groups-order: desc
  api-docs:
    path: /api-docs             # 문서화할 API 경로 패턴 지정
  paths-to-match:
    - /api/**                   # 기본 Request 미디어 타입
  default-consumes-media-type: application/json;charset=UTF-8   # 기본 Response 미디어 타입
  default-produces-media-type: application/json;charset=UTF-8